### ISSUE TITLE
Wrong sensor in the readme

### ISSUE THREAD

**Issue by davemcmath** [elyobelyob/octopus-energy-greenness-forecast-card#1]
there is an error in your readme in the YAML.

You put 

type: custom:octopus-energy-greenness-forecast-card
currentEntity: **event**.octopus_energy

It should read 

type: custom:octopus-energy-greenness-forecast-card
currentEntity: **sensor.**octopus_energy

**Comment by elyobelyob** [comment]
Thanks, I was a bit lazy on the documentation, fixed and also added future ... must spend time making sure it's fully configurable. Was in a bit of a rush!
