### ISSUE TITLE
Highlight emoji appears against multiple days

### ISSUE THREAD

**Issue by 3shirts** [elyobelyob/octopus-energy-greenness-forecast-card#5]
I might be misunderstanding how this works but I assumed the emoji would appear next to the greenest day in a given period but over the next 7 days I have it on three days, even though they have different greenness scores (albeit all high).
![image](https://github.com/user-attachments/assets/2078668b-9686-40b8-bb0e-95788b39e53d)

Is there just a threshold for when it gets highlighted or is there some other logic here?

**Comment by elyobelyob** [comment]
Octopus mark the days in the data, there's no "logic" within the app.
