### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by yebaws** [elyobelyob/octopus-energy-greenness-forecast-card#6]
Have followed installation instructions to the letter and have other Octopus cards successfully installed.

This card crashes my dashboard every time. It just goes blank and I have to re-install HA from a backup to get back all of my other cards

**Comment by elyobelyob** [comment]
Presumably you have installed Bottle Cap Dave's integration first? That's the only thing I could think of? 

Apart from that, I'd need some logs to diagnose? I have it running on my own HA as well as on a test server, with no issues.

**Comment by yebaws** [comment]
Thanks for the reply

Yes, have Bottle Cap Dave's integration running fine and use several sensors from it in automations. On restarting HA and seeing a completely blank dashboard, there is nothing in the error logs related to it, so I'm not sure how to troubleshoot it?

When the sensor includes <your_id_here>, does this mean my account id (eg: A-12345E6B) as I see on my Octopus account dashboard, or the id that includes my mpan (eg:19pXXXXXXX_170005324XXXX) as I use for the Octopus Energy integration? The card title displays if I use my account id (although it doesn't "work" - no greenness forecast) and the other cards on the dashboard show. But if I use the same "id" that I use for the Octopus Energy Integration, then the whole dashboard is blank.

I'm testing now on a dedicated test dashboard, so at least I don't need to backups to restore my cards.

**Comment by yebaws** [comment]
Fixed it. It was just a case of changing the account id letters to lower case (or just copying the entity from the list in HA). 

Strange that just having an incorrect entity can crash the entire dashboard though.

**Comment by elyobelyob** [comment]
I'll look into handling this in future.

**Comment by yebaws** [comment]
Great. Thanks for your work on the card.

**Comment by elyobelyob** [comment]
I was going to point out the "entity" itself. Feel free to update the docs with a more specific suggestion!
Currently updating my test bed with all the updates to test the three lines to fix the problem. 
Must setup a proper proxmox test bed or something.
